apiVersion: v1
kind: Service
metadata:
    name: client-service 
spec:
    type: NodePort
    selector:
        component: client
    ports:
     -  port: 8080
        targetPort: 3001
        protocol: TCP
        name: http